# Generated by Django 4.1.7 on 2024-01-21 15:58

import apiservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0003_alter_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subcategory', models.CharField(max_length=100, unique=True)),
                ('preview', models.ImageField(upload_to=apiservice.models.subcategory_preview_directory_path)),
                ('services', models.ManyToManyField(related_name='subcategory', to='apiservice.service')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, unique=True)),
                ('preview', models.ImageField(upload_to=apiservice.models.category_preview_directory_path)),
                ('subcategory', models.ManyToManyField(related_name='category', to='apiservice.subcategory')),
            ],
        ),
    ]
